sudo: false
language: c

env:
  global:
    - CGO_ENABLED: 1

matrix:
  include:
   - os: linux
     dist: xenial
     env:
      - PHP_INCLUDE: "-I/usr/include/php/20151012 -I/usr/include/php/20151012/main -I/usr/include/php/20151012/TSRM -I/usr/include/php/20151012/Zend -I/usr/include/php/20151012/ext -I/usr/include/php/20151012/ext/date/lib"
 
before_install:
  - go get github.com/gz-c/gox
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
  - cd $TRAVIS_BUILD_DIR
  - php -v
  - gcc -v
  - eval "$(gimme 1.11)"

script: make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify