language: php
sudo: false

env:
  global:
    - CGO_ENABLED: 1

matrix:
  include:
   - os: linux
     dist: bionic   
   - os: osx
 
before_install:
  - go get github.com/gz-c/gox
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-os.sh; fi
  - cd $TRAVIS_BUILD_DIR
  - php -v
  - eval "$(gimme 1.11)"

script: make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify