<?php
/**
 * NetworkConnectionSchemaUnconfirmedVerifyTransaction
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * NetworkConnectionSchemaUnconfirmedVerifyTransaction Class Doc Comment
 *
 * @category Class
 * @description Represent unconfirmed transactions
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NetworkConnectionSchemaUnconfirmedVerifyTransaction implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'networkConnectionSchema_unconfirmed_verify_transaction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'burn_factor' => 'int',
        'max_decimals' => 'int',
        'max_transaction_size' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'burn_factor' => 'int32',
        'max_decimals' => 'int32',
        'max_transaction_size' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'burn_factor' => 'burn_factor',
        'max_decimals' => 'max_decimals',
        'max_transaction_size' => 'max_transaction_size'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'burn_factor' => 'setBurnFactor',
        'max_decimals' => 'setMaxDecimals',
        'max_transaction_size' => 'setMaxTransactionSize'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'burn_factor' => 'getBurnFactor',
        'max_decimals' => 'getMaxDecimals',
        'max_transaction_size' => 'getMaxTransactionSize'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['burn_factor'] = isset($data['burn_factor']) ? $data['burn_factor'] : null;
        $this->container['max_decimals'] = isset($data['max_decimals']) ? $data['max_decimals'] : null;
        $this->container['max_transaction_size'] = isset($data['max_transaction_size']) ? $data['max_transaction_size'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets burn_factor
     *
     * @return int|null
     */
    public function getBurnFactor()
    {
        return $this->container['burn_factor'];
    }

    /**
     * Sets burn_factor
     *
     * @param int|null $burn_factor burn_factor
     *
     * @return $this
     */
    public function setBurnFactor($burn_factor)
    {
        $this->container['burn_factor'] = $burn_factor;

        return $this;
    }

    /**
     * Gets max_decimals
     *
     * @return int|null
     */
    public function getMaxDecimals()
    {
        return $this->container['max_decimals'];
    }

    /**
     * Sets max_decimals
     *
     * @param int|null $max_decimals max_decimals
     *
     * @return $this
     */
    public function setMaxDecimals($max_decimals)
    {
        $this->container['max_decimals'] = $max_decimals;

        return $this;
    }

    /**
     * Gets max_transaction_size
     *
     * @return int|null
     */
    public function getMaxTransactionSize()
    {
        return $this->container['max_transaction_size'];
    }

    /**
     * Sets max_transaction_size
     *
     * @param int|null $max_transaction_size max_transaction_size
     *
     * @return $this
     */
    public function setMaxTransactionSize($max_transaction_size)
    {
        $this->container['max_transaction_size'] = $max_transaction_size;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


