<?php
/**
 * WalletTransactionRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SkyApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.27.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SkyApi\Model;

use \ArrayAccess;
use \SkyApi\ObjectSerializer;

/**
 * WalletTransactionRequest Class Doc Comment
 *
 * @category Class
 * @package  SkyApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WalletTransactionRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'walletTransactionRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'changeAddress' => 'string',
        'hoursSelection' => '\SkyApi\Model\WalletTransactionRequestHoursSelection',
        'ignoreUnconfirmed' => 'bool',
        'to' => 'object[]',
        'wallet' => '\SkyApi\Model\WalletTransactionRequestWallet'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'changeAddress' => null,
        'hoursSelection' => null,
        'ignoreUnconfirmed' => null,
        'to' => null,
        'wallet' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'changeAddress' => 'change_address',
        'hoursSelection' => 'hours_selection',
        'ignoreUnconfirmed' => 'ignore_unconfirmed',
        'to' => 'to',
        'wallet' => 'wallet'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'changeAddress' => 'setChangeAddress',
        'hoursSelection' => 'setHoursSelection',
        'ignoreUnconfirmed' => 'setIgnoreUnconfirmed',
        'to' => 'setTo',
        'wallet' => 'setWallet'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'changeAddress' => 'getChangeAddress',
        'hoursSelection' => 'getHoursSelection',
        'ignoreUnconfirmed' => 'getIgnoreUnconfirmed',
        'to' => 'getTo',
        'wallet' => 'getWallet'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['changeAddress'] = isset($data['changeAddress']) ? $data['changeAddress'] : null;
        $this->container['hoursSelection'] = isset($data['hoursSelection']) ? $data['hoursSelection'] : null;
        $this->container['ignoreUnconfirmed'] = isset($data['ignoreUnconfirmed']) ? $data['ignoreUnconfirmed'] : null;
        $this->container['to'] = isset($data['to']) ? $data['to'] : null;
        $this->container['wallet'] = isset($data['wallet']) ? $data['wallet'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets changeAddress
     *
     * @return string|null
     */
    public function getChangeAddress()
    {
        return $this->container['changeAddress'];
    }

    /**
     * Sets changeAddress
     *
     * @param string|null $changeAddress changeAddress
     *
     * @return $this
     */
    public function setChangeAddress($changeAddress)
    {
        $this->container['changeAddress'] = $changeAddress;

        return $this;
    }

    /**
     * Gets hoursSelection
     *
     * @return \SkyApi\Model\WalletTransactionRequestHoursSelection|null
     */
    public function getHoursSelection()
    {
        return $this->container['hoursSelection'];
    }

    /**
     * Sets hoursSelection
     *
     * @param \SkyApi\Model\WalletTransactionRequestHoursSelection|null $hoursSelection hoursSelection
     *
     * @return $this
     */
    public function setHoursSelection($hoursSelection)
    {
        $this->container['hoursSelection'] = $hoursSelection;

        return $this;
    }

    /**
     * Gets ignoreUnconfirmed
     *
     * @return bool|null
     */
    public function getIgnoreUnconfirmed()
    {
        return $this->container['ignoreUnconfirmed'];
    }

    /**
     * Sets ignoreUnconfirmed
     *
     * @param bool|null $ignoreUnconfirmed ignoreUnconfirmed
     *
     * @return $this
     */
    public function setIgnoreUnconfirmed($ignoreUnconfirmed)
    {
        $this->container['ignoreUnconfirmed'] = $ignoreUnconfirmed;

        return $this;
    }

    /**
     * Gets to
     *
     * @return object[]|null
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param object[]|null $to to
     *
     * @return $this
     */
    public function setTo($to)
    {
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets wallet
     *
     * @return \SkyApi\Model\WalletTransactionRequestWallet|null
     */
    public function getWallet()
    {
        return $this->container['wallet'];
    }

    /**
     * Sets wallet
     *
     * @param \SkyApi\Model\WalletTransactionRequestWallet|null $wallet wallet
     *
     * @return $this
     */
    public function setWallet($wallet)
    {
        $this->container['wallet'] = $wallet;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


