<?php
/**
 * Apiv1pendingTxsTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Skyapi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Skyapi;

/**
 * Apiv1pendingTxsTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block
 * @package     Skyapi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Apiv1pendingTxsTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Apiv1pendingTxsTransaction"
     */
    public function testApiv1pendingTxsTransaction()
    {
    }

    /**
     * Test attribute "outputs"
     */
    public function testPropertyOutputs()
    {
    }

    /**
     * Test attribute "inner_hash"
     */
    public function testPropertyInnerHash()
    {
    }

    /**
     * Test attribute "inputs"
     */
    public function testPropertyInputs()
    {
    }

    /**
     * Test attribute "sigs"
     */
    public function testPropertySigs()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }
}
