<?php
/**
 * ApiV1PendingTxsTransactionOutputsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * ApiV1PendingTxsTransactionOutputsTest Class Doc Comment
 *
 * @category    Class
 * @description ApiV1PendingTxsTransactionOutputs
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ApiV1PendingTxsTransactionOutputsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApiV1PendingTxsTransactionOutputs"
     */
    public function testApiV1PendingTxsTransactionOutputs()
    {
    }

    /**
     * Test attribute "uxid"
     */
    public function testPropertyUxid()
    {
    }

    /**
     * Test attribute "dst"
     */
    public function testPropertyDst()
    {
    }

    /**
     * Test attribute "coins"
     */
    public function testPropertyCoins()
    {
    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {
    }
}
