<?php
/**
 * BlockVerboseSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Skyapi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Skyapi;

use PHPUnit\Framework\TestCase;

/**
 * BlockVerboseSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description BlockVerboseSchema
 * @package     Skyapi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BlockVerboseSchemaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BlockVerboseSchema"
     */
    public function testBlockVerboseSchema()
    {
    }

    /**
     * Test attribute "header"
     */
    public function testPropertyHeader()
    {
    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }
}
