<?php
/**
 * BlockVerboseSchemaHeaderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Skyapi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Skyapi;

use PHPUnit\Framework\TestCase;

/**
 * BlockVerboseSchemaHeaderTest Class Doc Comment
 *
 * @category    Class
 * @description BlockVerboseSchemaHeader
 * @package     Skyapi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BlockVerboseSchemaHeaderTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BlockVerboseSchemaHeader"
     */
    public function testBlockVerboseSchemaHeader()
    {
    }

    /**
     * Test attribute "seq"
     */
    public function testPropertySeq()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "block_hash"
     */
    public function testPropertyBlockHash()
    {
    }

    /**
     * Test attribute "previous_block_hash"
     */
    public function testPropertyPreviousBlockHash()
    {
    }

    /**
     * Test attribute "tx_body_hash"
     */
    public function testPropertyTxBodyHash()
    {
    }

    /**
     * Test attribute "ux_hash"
     */
    public function testPropertyUxHash()
    {
    }
}
