<?php
/**
 * InlineResponse2003UnconfirmedVerifyTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Skyapi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Skyapi;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2003UnconfirmedVerifyTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Represent unconfirmed transactions
 * @package     Skyapi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2003UnconfirmedVerifyTransactionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2003UnconfirmedVerifyTransaction"
     */
    public function testInlineResponse2003UnconfirmedVerifyTransaction()
    {
    }

    /**
     * Test attribute "burn_factor"
     */
    public function testPropertyBurnFactor()
    {
    }

    /**
     * Test attribute "max_transaction_size"
     */
    public function testPropertyMaxTransactionSize()
    {
    }

    /**
     * Test attribute "max_decimals"
     */
    public function testPropertyMaxDecimals()
    {
    }
}
