<?php
/**
 * InlineResponse2002Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Skyapi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Skyapi;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2002Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2002
 * @package     Skyapi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2002Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2002"
     */
    public function testInlineResponse2002()
    {
    }

    /**
     * Test attribute "outputs"
     */
    public function testPropertyOutputs()
    {
    }

    /**
     * Test attribute "inner_hash"
     */
    public function testPropertyInnerHash()
    {
    }

    /**
     * Test attribute "inputs"
     */
    public function testPropertyInputs()
    {
    }

    /**
     * Test attribute "fee"
     */
    public function testPropertyFee()
    {
    }

    /**
     * Test attribute "sigs"
     */
    public function testPropertySigs()
    {
    }

    /**
     * Test attribute "length"
     */
    public function testPropertyLength()
    {
    }

    /**
     * Test attribute "txid"
     */
    public function testPropertyTxid()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "timestamp"
     */
    public function testPropertyTimestamp()
    {
    }
}
