<?php
/**
 * InlineResponse200Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Skyapi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Skyapi;

/**
 * InlineResponse200Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200
 * @package     Skyapi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse200Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse200"
     */
    public function testInlineResponse200()
    {
    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {
    }

    /**
     * Test attribute "coins"
     */
    public function testPropertyCoins()
    {
    }

    /**
     * Test attribute "uxid"
     */
    public function testPropertyUxid()
    {
    }

    /**
     * Test attribute "owner_address"
     */
    public function testPropertyOwnerAddress()
    {
    }

    /**
     * Test attribute "spent_block_seq"
     */
    public function testPropertySpentBlockSeq()
    {
    }

    /**
     * Test attribute "spent_tx"
     */
    public function testPropertySpentTx()
    {
    }

    /**
     * Test attribute "time"
     */
    public function testPropertyTime()
    {
    }

    /**
     * Test attribute "src_block_seq"
     */
    public function testPropertySrcBlockSeq()
    {
    }

    /**
     * Test attribute "src_tx"
     */
    public function testPropertySrcTx()
    {
    }
}
