<?php
/**
 * InlineResponse2002Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2002Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2002
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2002Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2002"
     */
    public function testInlineResponse2002()
    {
    }

    /**
     * Test attribute "current_coinhour_supply"
     */
    public function testPropertyCurrentCoinhourSupply()
    {
    }

    /**
     * Test attribute "current_supply"
     */
    public function testPropertyCurrentSupply()
    {
    }

    /**
     * Test attribute "locked_distribution_addresses"
     */
    public function testPropertyLockedDistributionAddresses()
    {
    }

    /**
     * Test attribute "max_supply"
     */
    public function testPropertyMaxSupply()
    {
    }

    /**
     * Test attribute "total_coinhour_supply"
     */
    public function testPropertyTotalCoinhourSupply()
    {
    }

    /**
     * Test attribute "total_supply"
     */
    public function testPropertyTotalSupply()
    {
    }

    /**
     * Test attribute "unlocked_distribution_addresses"
     */
    public function testPropertyUnlockedDistributionAddresses()
    {
    }
}
