<?php
/**
 * InlineResponse2004Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Skyapi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: skycoin.doe@example.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Skyapi;

/**
 * InlineResponse2004Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2004
 * @package     Skyapi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2004Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2004"
     */
    public function testInlineResponse2004()
    {
    }

    /**
     * Test attribute "announced"
     */
    public function testPropertyAnnounced()
    {
    }

    /**
     * Test attribute "is_valid"
     */
    public function testPropertyIsValid()
    {
    }

    /**
     * Test attribute "checked"
     */
    public function testPropertyChecked()
    {
    }

    /**
     * Test attribute "received"
     */
    public function testPropertyReceived()
    {
    }

    /**
     * Test attribute "transaction"
     */
    public function testPropertyTransaction()
    {
    }
}
