<?php
/**
 * InlineResponse2003Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Skyapi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Skyapi;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2003Test Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2003
 * @package     Skyapi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineResponse2003Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineResponse2003"
     */
    public function testInlineResponse2003()
    {
    }

    /**
     * Test attribute "last_received"
     */
    public function testPropertyLastReceived()
    {
    }

    /**
     * Test attribute "last_sent"
     */
    public function testPropertyLastSent()
    {
    }

    /**
     * Test attribute "outgoing"
     */
    public function testPropertyOutgoing()
    {
    }

    /**
     * Test attribute "mirror"
     */
    public function testPropertyMirror()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "listen_port"
     */
    public function testPropertyListenPort()
    {
    }

    /**
     * Test attribute "is_trusted_peer"
     */
    public function testPropertyIsTrustedPeer()
    {
    }

    /**
     * Test attribute "connected_at"
     */
    public function testPropertyConnectedAt()
    {
    }

    /**
     * Test attribute "unconfirmed_verify_transaction"
     */
    public function testPropertyUnconfirmedVerifyTransaction()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "user_agent"
     */
    public function testPropertyUserAgent()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }
}
