<?php
/**
 * NetworkConnectionSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * NetworkConnectionSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description NetworkConnectionSchema
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class NetworkConnectionSchemaTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NetworkConnectionSchema"
     */
    public function testNetworkConnectionSchema()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "connected_at"
     */
    public function testPropertyConnectedAt()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_trusted_peer"
     */
    public function testPropertyIsTrustedPeer()
    {
    }

    /**
     * Test attribute "last_received"
     */
    public function testPropertyLastReceived()
    {
    }

    /**
     * Test attribute "last_sent"
     */
    public function testPropertyLastSent()
    {
    }

    /**
     * Test attribute "listen_port"
     */
    public function testPropertyListenPort()
    {
    }

    /**
     * Test attribute "mirror"
     */
    public function testPropertyMirror()
    {
    }

    /**
     * Test attribute "outgoing"
     */
    public function testPropertyOutgoing()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "unconfirmed_verify_transaction"
     */
    public function testPropertyUnconfirmedVerifyTransaction()
    {
    }

    /**
     * Test attribute "user_agent"
     */
    public function testPropertyUserAgent()
    {
    }
}
